export const INACTIVE = 'INACTIVE';
export const FLIP_RIGHT_TO_MIDDLE = 'FLIP_RIGHT_TO_MIDDLE';
export const FLIP_RIGHT_FROM_MIDDLE = 'FLIP_RIGHT_FROM_MIDDLE';
export const FLIP_LEFT_TO_MIDDLE = 'FLIP_LEFT_TO_MIDDLE';
export const FLIP_LEFT_FROM_MIDDLE = 'FLIP_LEFT_FROM_MIDDLE';
